### ISSUE TITLE
Allow trailing positional opts 

### ISSUE THREAD

**Issue by borkdude** [babashka/cli#13]
Git has this syntax:

```
git push <options> repo <refspec>
```

Currently this library does not parse that syntax since it expects all options after the initial commands / positionals.

To allow this, we'd have to introduce a strict mode, so all options are passed like `--foo` for booleans or `--foo=bar` for key-value pairs (and repeated ones for collections) so everything else become positional arguments.

Terminology from the mainstream: 

```
command subcommand --option args
```

**Comment by borkdude** [comment]
As discussed with @pesterhazy, enforcing the style `foo=bar` isn't really necessary if people provide enough information about the expected types. E.g. `--force foo bar` => `{:opts {:force true} :args ["foo" "bar"]}` can be produced when you know that `:force` is of type `:boolean` (and the next value could be omitted). Although we also support `--foo true`, so we'd still have the ambiguity if we do not enforce the strict style.

**Comment by borkdude** [comment]
If we require that multiple arguments to one option must be written down with a comma, the above becomes much easier to parse without ambiguity:

```
--add foo, bar, baz arg1 arg2
```

=> `{:add ["foo" "bar" "baz"] :args ["arg1 "arg2"]`

@pesterhazy How do you feel about that, too much magic or reasonable?

**Comment by borkdude** [comment]
I went with the least amount of magic:

https://github.com/babashka/cli#arguments

With sufficient information, the right thing will happen.

**Comment by pesterhazy** [comment]
I'm not an expert but personally speaking the comma seems unusual. What if
the arg itself ends with a comma?

**Comment by borkdude** [comment]
This issue has long been solved, see the last comment. Comma's did not make it in.
