### ISSUE TITLE
requiring a value be supplied for an option

### ISSUE THREAD

**Issue by flyingmachine** [babashka/cli#52]
clojure.tools.cli gives you a way to specify that a value must be supplied for an option by specifying the option with something like

```clojure
["-e" "--entry ENTRY" "Text of your entry"]
```

If your args include `--entry` but nothing after, it's treated as an error. Would it be possible to do something similar with this library? `:require` mandates the presence of an option, but doesn't handle the case where no value is supplied.

**Comment by borkdude** [comment]
I'd say this should fail with a required error:

``` clojure
user=> (cli/parse-opts ["--foo"] {:coerce {:foo :number}})
{:foo true}
```

and this should not, as booleans may just be the flag:

``` clojure
user=> (cli/parse-opts ["--foo"] {:coerce {:foo :boolean}})
{:foo true}
```

**Comment by flyingmachine** [comment]
Yeah, this looks right to me

**Comment by borkdude** [comment]
OK, I'm working on it
