### ISSUE TITLE
missing string option is parsed to "true"

### ISSUE THREAD

**Issue by trptr** [babashka/cli#57]
```clojure
(cli/parse-opts [":opt"] {:coerce {:opt :string}})
```

current:
```clojure
{:opt "true"}
```

expected:
```clojure
{:opt ""}
```

## Notes

**1.**
```clojure
(cli/parse-opts [":opt" "true"] {:coerce {:opt :string}})
```

current & expected:
```clojure
{:opt "true"}
```

**2.**
```clojure
(cli/parse-opts [":opt" ""] {:coerce {:opt :string}})
```

current & expected:
```clojure
{:opt ""}
```

So with my proposal above, we couldn't distinguish empty string ("") and missing value.
Similarly as "true" and missing value cannot be distinguished today.
(Unless a default is given with `:exec-args` -- but then we cannot distinguish if the default value is coming from the command line or from `:exec-args`.)

Ideally we should be able to distinguish all possibilities:

_a)_ the keyword (":opt", in the example above) is not in the parsed string list; e.g. `(cli/parse-opts [":else"] {:coerce {:opt :string}})`

_b)_ the keyword is there, but without specified value; e.g. `(cli/parse-opts [":opt"] {:coerce {:opt :string}})`

_c)_ the keyword is there with a specified invalid value; not possible with strings...

_d)_ the keyword is there with a specified valid value; e.g. `(cli/parse-opts [":opt" "true"] {:coerce {:opt :string}})`

But currently we can distinguish (in the worst case, e.g. when "true" is a valid value for an optional string opt) at most three of them: a, c and (b or d), if `:exec-args` is not used; when `:exec-args` is used, we can distinguish only two: (a or b or d) and c. 

Maybe the best would be not to parse options without values into :opts, but into a new collection, like
```clojure
(cli/parse-args [":opt"] {:coerce {:opt :string}})
{:nil-opts [:opt], :opts {}}
```
So at least when `parse-args` is used, all possible values could be distinguished.

**3.**
If it is boolean, we want to use true, as in current version, because it is [documented that way](https://github.com/babashka/cli#options):

```clojure
(cli/parse-opts [":opt"] {:coerce {:opt :boolean}})
```
current & expected:
```clojure
{:opt true}
```

**4.**
But if it is not boolean and not string, we may want to use true (as in current version) or throw.
I don't have strong opinion here, but I would argue to keep "nothing is true" an exception exclusively limited to booleans. So we should throw for e.g. `(cli/parse-opts [":opt"] {:coerce {:opt :keyword}})` (which currently gives `{:opt :true}`, which is a bug or feature as the handling for strings -- its cleanest handling might be `:nil-opts`, as proposed above).

**5.**
I am not really sure if the current behavior detailed above is a bug or a feature.
Also I am not really sure what would be the best handling. Some alternatives are mentioned above.

**6.**
To get "" for missing string option value, an easy fix is changing the last line of add-val from

`(assoc acc current-opt arg))))`

to

`(assoc acc current-opt (if (and implicit-true?
                                (= arg "true")) "" arg)))))`

**Comment by borkdude** [comment]
What about parsing it to `nil`?

**Comment by trptr** [comment]
For me, it seems to be an elegant solution.

However, I am not sure if it could cause troubles later (if applied to all types, except boolean): it would mean, that e.g. `{:coerce {:opt :keyword}}` may produce non-keyword value (`nil`). I.e. one should be extra defensive when the result of `parse-opts` is used:

```clojure
(inc (get (cli/parse-opts [":opt"] {:coerce {:opt :int}}) :opt 0))  ;; (inc nil)
;;java.lang.NullPointerException....
```

**Comment by borkdude** [comment]
The other option would be to not parse the option at all:

```
(cli/parse-opts [":opt"] {:coerce {:opt :string}})
;;=> {}
```

**Comment by borkdude** [comment]
Or another option could be to throw with an error message that there was too little input for the `:opt` option.

**Comment by trptr** [comment]
Both seem to be safer for me.

Simply not parsing it, would mean that we loose some info (i.e. we couldn't distinguish 2 a) and b) above). That's why I proposed the new `:nil-opts`.

Throwing is a simple and safe option, for the price being a bit less open/flexible in `parse-opts`.

**Comment by borkdude** [comment]
Throwing would be in line with providing an option that would not conform to the specified data type, e.g. providing `foo` when the `:coerce` option is `:long` for example. Maybe we can see this as a similar case.

**Comment by trptr** [comment]
:+1:
