### ISSUE TITLE
docs: consider revising validation point under main ideas

### ISSUE THREAD

**Issue by lread** [babashka/cli#63]
## First, Kudos!
The more I use babashka/cli, the more I like it!

## Currently
The readme [states](https://github.com/babashka/cli/blob/d011ad3516be08c829a98013b3839d10b5e4fef2/README.md?plain=1#L48-L52):

> Because the line between calling functions from the command line and Clojure itself is blurred, validation of arguments should happen in your Clojure function, using your favorite tools (manually, spec, schema, malli...). As such, the library only focuses on coercion: turning argument strings into data which is then passed to your function.

I expect, it was after this was originally written, that babashka/cli has added argument validation support.

A use case I am looking at is using babashka/cli for an existing Clojure JVM project that supports both `-M` and `-X` invocations (the latter via [Clojure tools](https://clojure.org/reference/deps_and_cli#_tool_usage)).  

I would love to share validation for both of these entrypoints, but I don't think that is a goal of babashka/cli. Perhaps [babahka/bbin](https://github.com/babashka/bbin) is a command-line-friendly alternative to Clojure tools.

## So maybe
1. Update the quoted idea above. It is still valid to validate in-function if you need validation to occur for multiple entry-points, but it is no longer true that babashka/cli focuses only on coercion.
2. Maybe add some words on how babashka/cli is not in the business of directly making `-X` style invocations more command-line friendly, but it certainly can make command-line friendly `-M` style invocations that can delegate to `-X` targets.
3. Consider adding a pointer/tip for babashka/bbin as a potential command-line-friendly alternative to Clojure Tools. Is that a goal of bbin?

## Next Steps
There is always a good chance that I've misunderstood - maybe some or all of the above is not correct. Lemme know.

If you are interested, I can draft up doc changes in a PR for your review.

**Comment by borkdude** [comment]
I think you can validate with you use the `:validate` option in your `:org.babashka/cli` metadata, right? Yes, that part was written before that existed, but the validation will only happen if you invoke the function through babashka CLI.

**Comment by borkdude** [comment]
Thanks for the compliment btw!

**Comment by lread** [comment]
Oh, apologies, I forgot to follow up! Thanks for the response, makes sense, of course.

Jet is an example project that supports both `-X` and `-M` calling styles with [shared processing/validation](https://github.com/borkdude/jet/blob/9cd22dc3b99943ea0f7684c438442cf47b6a3384/src/jet/main.clj#L169).

I'm not sure this even needs to be clarified in the README, but can-do if you want.
Otherwise, feel free to close this sissue.

**Comment by borkdude** [comment]
Yeah, I think it would help

**Comment by borkdude** [comment]
I just deleted the confusing section.
