### ISSUE TITLE
Subcommand improvements: 

### ISSUE THREAD

**Issue by borkdude** [babashka/cli#66]
This is a meta-issue and we can make separate issues out of this.

## Documentation

The current dispatch table does not allow adding documentation generation.

## Subcommand specific options

See e.g.  https://github.com/agorgl/wgctl/blob/master/test/agorgl/wgctl/cli_test.clj#L102 which supports this.

```
(parse-args spec ["farmctl" "-f" "littlefarm" "animal" "-b" "cozyhouse" "add" "cow" "george"])
=>
[{:command ["farmctl"],
  :options {:farm "littlefarm"},
  :arguments {},
  :errors ()}
 {:command ["farmctl" "animal"],
  :options {:barn "cozyhouse"},
  :arguments {},
  :errors ()}
 {:command ["farmctl" "animal" "add"],
  :options {},
  :arguments {:type "cow", :name "george"},
  :errors ()}]

(not sure about this exact format, but interesting idea)

Also see https://github.com/clap-rs/clap

**Comment by jcf** [comment]
Problem I'm currently wrestling with is supplying global options.

``` sh
my-cli --no-color subcommand --foo bar
```

It's reasonably common and makes sense to pass options in both places. Not sure if this is within scope but pretty sure it's something I'll need to implement.

**Comment by borkdude** [comment]
You can do this right now by first using parse-args, which splits the opts
from the remaining args and then throw the latter through dispatch

**Comment by borkdude** [comment]
@jcf This should now be possible with 0.8.55:

``` clojure
(require '[babashka.cli :as cli])

(def table
  [{:cmds [] :spec {:color {:coerce :boolean}}}
   {:cmds ["subcommand"] :fn identity :spec {:foo {:coerce :keyword}}}])

(cli/dispatch table ["--no-color" "subcommand" "--foo" "bar"])
```

=>

``` clojure
{:dispatch ["subcommand"], :opts {:color false, :foo :bar}}
```

**Comment by borkdude** [comment]
Is it possible to post a stacktrace and/or an isolated example or push this to a Github repo which reproduces the NPE?

**Comment by borkdude** [comment]
And also the code/command line arguments to cause the NPE. I just tried your code and replaced / removed all `ui/*` stuff. 
This worked for me:

``` clojure
user=> (cli/execute ["new"])
{:dispatch ["new"], :opts {:color true, :verbose []}, :args nil}
user=> (cli/execute [])
{:dispatch [], :opts {}, :args []}
```

**Comment by lunik1** [comment]
Has the ability to generate documentation when using a dispatch table also been added?

**Comment by borkdude** [comment]
Do you mean `--help` output?

**Comment by lunik1** [comment]
Yes

**Comment by borkdude** [comment]
I've done some thinking on this but I wasn't sure which format would be appropriate for (nested) subcommands.
Do you have any suggestions?

**Comment by devurandom** [comment]
> I've done some thinking on this but I wasn't sure which format would be appropriate for (nested) subcommands. Do you have any suggestions?

Maybe:
```
$ example
Commands:
cmd1  First command
cmd2  Second command
help  Show help about command

Global options:
--foo Bar


$ example help cmd1
cmd1:
  --baz  Bar

Global options:
  --foo  Bar


$ example help cmd2
cmd2:
  --bax  Bar

Global options:
  --foo  Bar
```

**Comment by borkdude** [comment]
There is now an open issue about this here: https://github.com/babashka/cli/issues/112
