### ISSUE TITLE
Restrict option only works with keywords

### ISSUE THREAD

**Issue by hkjels** [babashka/cli#71]
- When `:no-keyword-opts` is set to `false` and `:restrict` is set to `true`:
  - Flags that are not in the specification will cause the `:error-fn` to be issued, with the `cause` set to `:restrict`, as expected.

- When `:no-keyword-opts` is set to `true` and `:restrict` is set to `true`:
  - All flags passed, regardless of whether they are in the specification or not, will cause the `:error-fn` to be issued with `cause` set to `:restrict`. Not expected.

**Comment by borkdude** [comment]
Repro:

```
user=> (cli/parse-opts ["--foo" "--bar"] {:no-keyword-opts true :restrict true})
Execution error (ExceptionInfo) at babashka.cli/parse-opts$fn (cli.cljc:314).
Unknown option: :foo
```

**Comment by borkdude** [comment]
@hkjels I thought I had a repro, but it wasn't correct.
The below acts as expected, right?
Can you make a repro that works not as expected?

```
user=> (cli/parse-opts ["--foo" "--bar"] {:no-keyword-opts true :restrict true :spec {:foo {:coerce :boolean} :bar {:coerce :boolean}} })
{:foo true, :bar true}
```

**Comment by hkjels** [comment]
I've reactivated the previously problematic code, and it now functions correctly. I'm uncertain about the initial cause, but I apologize for wasting your time.
