### ISSUE TITLE
Unknown option when alias begins with other alias

### ISSUE THREAD

**Issue by arichiardi** [babashka/cli#82]
Hi there!

I have the following `:spec`:

```clojure
:verbose {:desc "Enable verbose output." :alias :v}
   :very-verbose {:desc "Enable very verbose output." :alias :vv}
```

That when I `cli/parse-args` returns the unknown option error (via the `:error-fn`): 

```clojure
{:spec {:verbose {:desc "Enable verbose output.", :alias :v}
        :very-verbosd {:desc "Enable very verbose output.", :alias :vv}}
 :type :org.babashka/cli, :cause :restrict, :msg "Unknown option:" :e
 :restrict #{:check :verbose :fix :very-verbosd}, :option :e}
```

I could reproduce it only when `:vv` is used as `:alias`.

Using `bb --version babashka v1.3.186`.

**Comment by borkdude** [comment]
Can you please post a full repro, not just some fragments? I'm not sure how to reproduce your problem. What arguments are you parsing for example.

**Comment by borkdude** [comment]
I assume that this is your full repro:

```
(require '[babashka.cli :as cli] :reload)

(prn
 (cli/parse-opts
  ["-vv"]
  {:spec {:verbose {:desc "Enable verbose output.", :alias :v}
          :very-verbosd {:desc "Enable very verbose output.", :alias :vv}}
   :closed true}))
```

**Comment by borkdude** [comment]
One way to allow multiple aliases to be used is this:

```
(prn
 (cli/parse-opts
  ["-vv"]
  {:spec {:verbose {:coerce []
                    :desc "Enable verbose output.", :alias :v}}
   :closed true}))
```

which results into this:
``` clojure
{:verbose [true true]}
```

**Comment by borkdude** [comment]
I do consider the above as a bug which I'll fix though

**Comment by arichiardi** [comment]
Just woke up on this side of the world with awesome news thank you! Next time I'll make a repro sorry about that.

**Comment by borkdude** [comment]
Also released a new bb version. Perhaps it would be good to document that above usage of `-vv`?

**Comment by arichiardi** [comment]
I can do that

**Comment by borkdude** [comment]
Thanks very much!

**Comment by arichiardi** [comment]
@borkdude while checking the docs I noticed this 

> Flags may be combined into a single short option (since 0.7.51):

``` clojure
(cli/parse-opts ["-abc"])
;;=> {:a true :b true :c true}
```

And I was wondering if the following is also a (smaller) bug:

``` clojure
 (prn (cli/parse-opts ["-vvv"]))           
 {:v true}
```

I can change the docs to say that only "single letter" flags behave that way. Thoughts?
