### ISSUE TITLE
expose prefix in dispatch error no-match and input-exhausted cases

### ISSUE THREAD

**Issue by Sohalt** [babashka/cli#92]
It would be helpful to have the `cmds` https://github.com/babashka/cli/blob/05868bfb0b613d745b62abcd2340d0cf2017ea7b/src/babashka/cli.cljc#L638 also exposed in the error data for the `:no-match` and `:input-exhausted` cases, because it's helpful to know how far `dispatch` traversed the command tree until it encountered the error to give better error messages.

Specifically, if I have
```clojure
(def cmd-table
  [{:cmds ["foo" "bar"] :fn identity}
   {:cmds ["foo" "baz"] :fn identity}])
(dispatch cmd-table ["foo" "quux"] {:error-fn identity})
;; => {:type :org.babashka/cli, :wrong-input "quux", :all-commands ("bar" "baz"), :cause :no-match, :opts {}}
```
if I had the prefix "foo", I could genenrate an error message that lists all valid commands with prefix "foo" (i.e. "foo bar" "foo baz").

**Comment by borkdude** [comment]
Feel free to submit a PR, I prefer this to be called `:cmds` since that's what it's also called in the dispatch table?

**Comment by Sohalt** [comment]
It's called `:cmds` in the dispatch table, but is (and was) called `:dispatch` in the args to the fn called by `dispatch`. I don't have strong opinions though.

**Comment by borkdude** [comment]
Nowhere in a public API is the name `:dispatch` exposed right? (I mean on master, not in a previous WIP PR)

**Comment by Sohalt** [comment]
It is (and was) exposed on master as part of the `dispatch` fn, first introduced here https://github.com/babashka/cli/commit/72edb2896c5ae2daacd9825b72e352081bc5a7fb#diff-17c5192974650f8980e4dbdaa029b04d0ee52e3f3d77afc46a1944d79448aa0bR214

**Comment by Sohalt** [comment]
Wait, looks https://github.com/babashka/cli/commit/c870e2402437e1a9ac5dc6c4f9758b91a220800e removed it again.
But https://github.com/babashka/cli/commit/712fee82e0c64a0bf32b63b5d669647edcf17f20#diff-17c5192974650f8980e4dbdaa029b04d0ee52e3f3d77afc46a1944d79448aa0bR634 reintroduced it.
The docs listed it the entire time https://github.com/babashka/cli/blob/05868bfb0b613d745b62abcd2340d0cf2017ea7b/API.md?plain=1#L77, which is what I was looking at when implementing the dispatch-tree changes.
