### ISSUE TITLE
Unknown option: `:babashka.cli/opts-by-cmds` when using `dispatch` with `:restrict true`

### ISSUE THREAD

**Issue by ferdinand-beyer** [babashka/cli#98]
Reproducing example for `babashka/cli` **v0.8.59**:

```clojure
(cli/dispatch [{:cmds ["foo"]
                :fn identity
                :spec {:x {:coerce :boolean}}}]
              ["foo"]
              {:restrict true})
; => ExceptionInfo: Unknown option: :babashka.cli/opts-by-cmds
```

It seems like the special key `:babashka.cli/opts-by-cmds` is added to the config, and `:restrict true` then complains that this is not defined.

**Comment by borkdude** [comment]
Hmm, this is indeed a silly bug, thanks for posting.

**Comment by borkdude** [comment]
@ferdinand-beyer Do you need a new release or can you test/use as a git dep for now?

**Comment by ferdinand-beyer** [comment]
> @ferdinand-beyer Do you need a new release or can you test/use as a git dep for now?

I have a workaround for this and can wait for a release whenever it makes sense!
